// Auto-generated from Restaurants.xlsx — do not edit by hand
import Foundation

struct SeedRestaurant {
    let name: String
    let park: String
    let resort: String
    let category: String
    let isVisited: Bool
    let mattRating: Double
    let wifeRating: Double
}

let allSeedRestaurants: [SeedRestaurant] = [

    // MARK: - Walt Disney World
    SeedRestaurant(name: "1900 Park Fare", park: "Grand Floridian Resort", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "4 Rivers Cantina Barbacoa Food Truck", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "50's Prime Time Café", park: "Hollywood Studios", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "ABC Commissary", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Akershus Royal Banquet Hall", park: "EPCOT", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Ale & Compass Restaurant", park: "Yacht Club Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Amare", park: "Swan Reserve", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "B.B. Wolf's Sausage Co.", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Backlot Express", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Banana Cabana", park: "Caribbean Beach Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Be Our Guest Restaurant", park: "Magic Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Beach Club Marketplace", park: "Beach Club Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Beaches & Cream Soda Shop", park: "Beach Club Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Biergarten Restaurant", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Blaze Fast-Fire'd Pizza", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "BoardWalk Deli", park: "BoardWalk", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Boatwright's Dining Hall", park: "Port Orleans Riverside", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Boma - Flavors of Africa", park: "Animal Kingdom Lodge", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "California Grill", park: "Contemporary Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Capa", park: "Four Seasons Orlando", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cape May Cafe", park: "Beach Club Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Capt. Cook's", park: "Polynesian Village Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Casey's Corner", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Catalina Eddie's", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Centertown Market", park: "Caribbean Beach Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Chef Art Smith's Homecomin'", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Chef Mickey's", park: "Contemporary Resort", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Chefs de France", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Chicken Guy!", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Chip 'n' Dale's Deli", park: "Saratoga Springs Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cinderella's Royal Table", park: "Magic Kingdom", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cítricos", park: "Grand Floridian Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "City Works Eatery & Pour House", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Columbia Harbour House", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Connections Eatery", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Contempo Café", park: "Contemporary Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cookes of Dublin", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Coral Reef Restaurant", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cosmic Ray's Starlight Café", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "D-Luxe Burger", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Docking Bay 7 Food and Cargo", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Dockside Diner", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Earl of Sandwich®", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "eet by Maneet Chauhan", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "El Mercado de Coronado", park: "Coronado Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "End Zone Food Court", park: "All-Star Sports Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Enzo's Hideaway", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "ESPN Wide World of Sports Grill", park: "ESPN Wide World of Sports", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Everything POP Shopping & Dining", park: "Pop Century Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Fairfax Fare", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Flame Tree Barbecue", park: "Animal Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Flying Fish", park: "BoardWalk", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Garden Grill Restaurant", park: "EPCOT", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Garden Grove", park: "Swan Hotel", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Gasparilla Island Grill", park: "Grand Floridian Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Geyser Point Bar & Grill", park: "Wilderness Lodge", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Grand Floridian Cafe", park: "Grand Floridian Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Harambe Market", park: "Animal Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Hollywood & Vine", park: "Hollywood Studios", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Hoop-Dee-Doo Musical Revue", park: "Fort Wilderness", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "House of Blues Restaurant & Bar", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Il Mulino", park: "Walt Disney World Swan", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Intermission Food Court", park: "All-Star Music Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Jaleo by José Andrés", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Jiko - The Cooking Place", park: "Animal Kingdom Lodge", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Jungle Navigation Co. LTD Skipper Canteen", park: "Magic Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Kabuki Cafe", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Katsura Grill", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Kimonos", park: "Swan Hotel", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Kona Cafe", park: "Polynesian Village Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "La Cantina de San Angel", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "La Crêperie de Paris", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "La Hacienda de San Angel", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Landscape of Flavors", park: "Art of Animation Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Le Cellier Steakhouse", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Leaning Palms", park: "Typhoon Lagoon", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Les Halles Boulangerie-Patisserie", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Liberty Tree Tavern", park: "Magic Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Lottawatta Lodge", park: "Blizzard Beach", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Lotus Blossom Café", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Mama Melrose's Ristorante Italiano", park: "Hollywood Studios", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Maria & Enzo's Ristorante", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Maya Grill", park: "Coronado Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Monsieur Paul", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Morimoto Asia", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Narcoossee's", park: "Grand Floridian Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Nine Dragons Restaurant", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Ohana", park: "Polynesian Village Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Olivia's Cafe", park: "Old Key West Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Paddlefish", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pecos Bill Tall Tale Inn and Cafe", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pepe by José Andrés", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Picabu", park: "Dolphin Hotel", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pinocchio Village Haus", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pizza Ponte", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pizzafari", park: "Animal Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "PizzeRizzo", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Planet Hollywood", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Primo Piatto", park: "Riviera Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Raglan Road™ Irish Pub and Restaurant", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Rainforest Cafe®", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Ravello", park: "Four Seasons Orlando", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Regal Eagle Smokehouse: Craft Drafts & Barbecue", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Restaurantosaurus", park: "Animal Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Riverside Mill Food Court", park: "Port Orleans Riverside", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Rix Sports Bar & Grill", park: "Coronado Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Roaring Fork", park: "Wilderness Lodge", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Ronto Roasters", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Rose & Crown Dining Room", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Rosie's All-American Café", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Roundup Rodeo BBQ", park: "Hollywood Studios", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "San Angel Inn Restaurante", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Sanaa", park: "Animal Kingdom Lodge", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Satu'li Canteen", park: "Animal Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Sci-Fi Dine-In Theater Restaurant", park: "Hollywood Studios", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Sebastian's Bistro", park: "Caribbean Beach Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Shiki-Sai: Sushi Izakaya", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Sleepy Hollow", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Space 220", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Spice Road Table", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Splitsville Dining Room", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Spyglass Grill", park: "Caribbean Beach Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Steakhouse 71", park: "Contemporary Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "STK® Steakhouse", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Story Book Dining at Artist Point with Snow White", park: "Wilderness Lodge", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Summer House on the Lake", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Sunshine Seasons", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "T-REX™", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Takumi-Tei", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Tangerine", park: "Swan Reserve", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Teppan Edo", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Terralina Crafted Italian", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Artist's Palette", park: "Saratoga Springs Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The BOATHOUSE®", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Chuck Wagon", park: "Fort Wilderness", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Crystal Palace", park: "Magic Kingdom", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Daily Poutine", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Dining Room at Victoria & Albert's", park: "Grand Floridian Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Edison", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Fountain", park: "Dolphin Hotel", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Friar's Nook", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Hollywood Brown Derby", park: "Hollywood Studios", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Lunching Pad", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Mara", park: "Animal Kingdom Lodge", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Plaza Restaurant", park: "Magic Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Polite Pig", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Turf Club Bar and Grill", park: "Saratoga Springs Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Three Bridges Bar and Grill at Villa del Lago", park: "Coronado Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Tiffins Restaurant", park: "Animal Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Todd English's bluezoo", park: "Dolphin Hotel", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Toledo - Tapas, Steak & Seafood", park: "Coronado Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Tony's Town Square Restaurant", park: "Magic Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Topolino's Terrace - Flavors of the Riviera", park: "Riviera Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Tortuga Tavern", park: "Magic Kingdom", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Trail's End Restaurant", park: "Fort Wilderness", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Trattoria al Forno", park: "BoardWalk", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Tusker House Restaurant", park: "Animal Kingdom", resort: "Walt Disney World", category: "Character Dining", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Tutto Italia Ristorante", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Typhoon Tilly's", park: "Typhoon Lagoon", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Via Napoli Ristorante e Pizzeria", park: "EPCOT", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Whispering Canyon Café", park: "Wilderness Lodge", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Wine Bar George", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Wolfgang Puck Bar & Grill", park: "Disney Springs", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Woody's Lunch Box", park: "Hollywood Studios", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "World Premiere Food Court", park: "All-Star Movies Resort", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Yachtsman Steakhouse", park: "Yacht Club Resort", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Yak & Yeti™ Restaurant", park: "Animal Kingdom", resort: "Walt Disney World", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "YeSake Kiosk", park: "Disney Springs", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Yorkshire County Fish Shop", park: "EPCOT", resort: "Walt Disney World", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),

    // MARK: - Universal Orlando
    SeedRestaurant(name: "Amatista Cookhouse", park: "Sapphire Falls Resort", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Antojitos Authentic Mexican Food", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bayliner Diner", park: "Cabana Bay Beach Resort", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Beach Break Cafe", park: "Endless Summer Surfside", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bend the Bao", park: "CityWalk", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bice Ristorante", park: "Portofino Bay Hotel", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bigfire", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Blondie's", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bob Marley-A Tribute to Freedom", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bread Box Handcrafted Sandwiches", park: "CityWalk", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bubba Gump Shrimp Co.™ Restaurant & Market", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bula Bar & Grille", park: "Royal Pacific Resort", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Bumblebee Man's Taco Truck", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cafe 4™", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cafe La Bamba", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Captain America Diner®", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Circus McGurkus Cafe Stoo-pendous™", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Cletus' Chicken Shack", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Comic Strip Cafe", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Confisco Grille", park: "Islands of Adventure", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Doc Sugrue's Desert Kebab House", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Drhum Club Kantine", park: "Sapphire Falls Resort", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Finnegan's Bar & Grill", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Fire Eater's Grill", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Galaxy Bowl Restaurant", park: "Cabana Bay Beach Resort", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Green Eggs and Ham™ Cafe", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Hard Rock Cafe® Orlando", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Hot Dog Hall of Fame®", park: "CityWalk", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Minion Cafe", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Islands Dining Room", park: "Royal Pacific Resort", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Jake's American Bar", park: "Royal Pacific Resort", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Jimmy Buffett's® Margaritaville®", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Kohola Reef Restaurant & Social Club", park: "Volcano Bay", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Krusty Burger", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Leaky Cauldron™", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Lombard's Seafood Grille", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Louie's Italian Restaurant", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Luigi's Pizza", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Mama Della's Ristorante", park: "Portofino Bay Hotel", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Mel's Drive-In", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Mythos Restaurant", park: "Islands of Adventure", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "NBC Sports Grill & Brew™", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Orchid Court Lounge & Sushi Bar", park: "Royal Pacific Resort", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pat O'Brien's®", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pier 8 Market", park: "Endless Summer Dockside", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Pizza Predattoria", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Red Oven Pizza Bakery", park: "CityWalk", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Richter's Burger Co.", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Sal's Market Deli", park: "Portofino Bay Hotel", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Splendido Bar & Grill™", park: "Portofino Bay Hotel", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Burger Digs", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Cowfish® Sushi Burger Bar", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Feasting Frog", park: "Volcano Bay", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Frying Dutchman", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Hideaway Bar & Grill", park: "Cabana Bay Beach Resort", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Kitchen", park: "Hard Rock Hotel", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Palm", park: "Hard Rock Hotel", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "The Toothsome Chocolate Emporium and Savory Feast Kitchen", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Three Broomsticks™", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Thunder Falls Terrace", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "TODAY Cafe", park: "Universal Studios Florida", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Trattoria del Porto", park: "Portofino Bay Hotel", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "VIVO Italian Kitchen", park: "CityWalk", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Whakawaiwai Eats", park: "Volcano Bay", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Wimpy's", park: "Islands of Adventure", resort: "Universal Orlando", category: "Quick Service", isVisited: false, mattRating: 0, wifeRating: 0),
    SeedRestaurant(name: "Wine Riffs", park: "Hard Rock Hotel", resort: "Universal Orlando", category: "Table Service", isVisited: false, mattRating: 0, wifeRating: 0)
]



// MARK: - Seed Hotels

struct SeedHotel {
    let name: String
    let resort: String
    let tier: String
}

let allSeedHotels: [SeedHotel] = [
    // MARK: Walt Disney World – Deluxe
    SeedHotel(name: "Disney's Grand Floridian Resort & Spa", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's Contemporary Resort", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's Polynesian Village Resort", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's Wilderness Lodge", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's Animal Kingdom Lodge", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's BoardWalk Inn", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's Beach Club Resort", resort: "Walt Disney World", tier: "Deluxe"),
    SeedHotel(name: "Disney's Yacht Club Resort", resort: "Walt Disney World", tier: "Deluxe"),

    // MARK: Walt Disney World – DVC
    SeedHotel(name: "Disney's Old Key West Resort", resort: "Walt Disney World", tier: "Disney Vacation Club"),
    SeedHotel(name: "Disney's Saratoga Springs Resort & Spa", resort: "Walt Disney World", tier: "Disney Vacation Club"),
    SeedHotel(name: "Disney's Riviera Resort", resort: "Walt Disney World", tier: "Disney Vacation Club"),
    SeedHotel(name: "Disney's Polynesian Villas & Bungalows", resort: "Walt Disney World", tier: "Disney Vacation Club"),
    SeedHotel(name: "Disney's Animal Kingdom Villas – Kidani Village", resort: "Walt Disney World", tier: "Disney Vacation Club"),
    SeedHotel(name: "Disney's Bay Lake Tower", resort: "Walt Disney World", tier: "Disney Vacation Club"),
    SeedHotel(name: "Disney's BoardWalk Villas", resort: "Walt Disney World", tier: "Disney Vacation Club"),

    // MARK: Walt Disney World – Moderate
    SeedHotel(name: "Disney's Coronado Springs Resort", resort: "Walt Disney World", tier: "Moderate"),
    SeedHotel(name: "Disney's Caribbean Beach Resort", resort: "Walt Disney World", tier: "Moderate"),
    SeedHotel(name: "Disney's Port Orleans Resort – French Quarter", resort: "Walt Disney World", tier: "Moderate"),
    SeedHotel(name: "Disney's Port Orleans Resort – Riverside", resort: "Walt Disney World", tier: "Moderate"),

    // MARK: Walt Disney World – Value
    SeedHotel(name: "Disney's All-Star Movies Resort", resort: "Walt Disney World", tier: "Value"),
    SeedHotel(name: "Disney's All-Star Music Resort", resort: "Walt Disney World", tier: "Value"),
    SeedHotel(name: "Disney's All-Star Sports Resort", resort: "Walt Disney World", tier: "Value"),
    SeedHotel(name: "Disney's Art of Animation Resort", resort: "Walt Disney World", tier: "Value"),
    SeedHotel(name: "Disney's Pop Century Resort", resort: "Walt Disney World", tier: "Value"),

    // MARK: Walt Disney World – Other
    SeedHotel(name: "Disney's Fort Wilderness Resort & Campground", resort: "Walt Disney World", tier: "Campground"),
    SeedHotel(name: "Disney's Shades of Green Resort", resort: "Walt Disney World", tier: "Military"),
    SeedHotel(name: "Walt Disney World Swan", resort: "Walt Disney World", tier: "Partner Hotel"),
    SeedHotel(name: "Walt Disney World Dolphin", resort: "Walt Disney World", tier: "Partner Hotel"),
    SeedHotel(name: "Walt Disney World Swan Reserve", resort: "Walt Disney World", tier: "Partner Hotel"),
    SeedHotel(name: "Four Seasons Orlando at Walt Disney World Resort", resort: "Walt Disney World", tier: "Partner Hotel"),

    // MARK: Universal Orlando – Premier
    SeedHotel(name: "Loews Portofino Bay Hotel", resort: "Universal Orlando", tier: "Premier"),
    SeedHotel(name: "Hard Rock Hotel Orlando", resort: "Universal Orlando", tier: "Premier"),
    SeedHotel(name: "Loews Royal Pacific Resort", resort: "Universal Orlando", tier: "Premier"),

    // MARK: Universal Orlando – Preferred
    SeedHotel(name: "Loews Sapphire Falls Resort", resort: "Universal Orlando", tier: "Preferred"),

    // MARK: Universal Orlando – Standard & Value
    SeedHotel(name: "Universal's Cabana Bay Beach Resort", resort: "Universal Orlando", tier: "Standard"),
    SeedHotel(name: "Universal's Aventura Hotel", resort: "Universal Orlando", tier: "Standard"),
    SeedHotel(name: "Universal's Endless Summer Resort – Surfside Inn and Suites", resort: "Universal Orlando", tier: "Value"),
    SeedHotel(name: "Universal's Endless Summer Resort – Dockside Inn and Suites", resort: "Universal Orlando", tier: "Value"),

    // MARK: Universal Orlando – Epic Universe Hotels
    SeedHotel(name: "Universal Helios Grand Hotel", resort: "Universal Orlando", tier: "Premier"),
    SeedHotel(name: "Universal Stella Nova Resort", resort: "Universal Orlando", tier: "Standard"),
    SeedHotel(name: "Universal Terra Luna Resort", resort: "Universal Orlando", tier: "Standard"),
]

